version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

jobs:
  build-test:
    docker:
      - image: cimg/openjdk:17.0.3
    environment:
      PORT: 5000
      REDIRECT_URL: 'http://127.0.0.1:5000/simple_get'
    steps:
      - checkout
      - run:
          name: Run test
          command: ./gradlew test
      - codecov/upload
      - run:
          name: coverage
          command: bash <(curl -s https://codecov.io/bash)
  deploy-ec2:
    docker:
      - image: cimg/openjdk:17.0.3
      environment:
        PORT: 5000
        REDIRECT_URL: 'http://127.0.0.1:5000/simple_get'
    steps:
      - checkout
      - run:
          name: build jar
          command: ./gradlew clean build jar
      - run:
          name: copy jar to ec2 instance
          command: scp $JAR_PATH ec2-user@$EC2_IP

workflows:
  build-test-workflow:
    jobs:
      - build-test
      - deploy-ec2:
          filters:
            branches:
              only: test-deploy
