version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

jobs:
  build-test:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run:
          name: Run build
          command: |
#            PORT=5000
#            REDIRECT_URL="http://127.0.0.1:5000/simple_get"
            ./gradlew clean build
      - run:
          name: Run test
          command: |
#            PORT=5000
#            REDIRECT_URL="http://127.0.0.1:5000/simple_get"
            ./gradlew test


  upload-to-codecov:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run:
          name: port
          command: export PORT=5000
      - run:
          name: redirect url
          command: export REDIRECT_URL="http://127.0.0.1:5000/simple_get"
      - run:
          name: Run test
          command: ./gradlew test
      - codecov/upload
      - run:
          name: coverage
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  build-test-workflow:
    jobs:
      - build-test
  upload-to-codecov-workflow:
    jobs:
      - upload-to-codecov
