version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3

jobs:
  build-test:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run:
          name: Run build
          command: ./gradlew build
      - run:
          name: Run test
          command: ./gradlew test

test:
  post:
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
    - bash <(curl -s https://codecov.io/bash)

workflows:
  build-test-workflow:
    jobs:
      - build-test
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload
