version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

jobs:
  build-test:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run:
          name: Run build
          command: ./gradlew build
      - run:
          name: Run test
          command: ./gradlew test
#      - codecov/upload
#      - run:
#          name: coverage
#          command: bash <(curl -s https://codecov.io/bash)

  upload-to-codecov:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
#      - codecov/upload
      - run:
          name: Run test
          command: ./gradlew test
      - codecov/upload
      - run:
          name: coverage
          command: bash <(curl -s https://codecov.io/bash)
#          with:
#            file: ./coverage.xml
#            verbose: true

workflows:
  build-test-workflow:
    jobs:
      - build-test
  upload-to-codecov-workflow:
    jobs:
      - upload-to-codecov
